### ISSUE TITLE
Best Practices for Generating Principals in Express-Azle

### ISSUE THREAD

**Issue by wirapratamaz** [adrian-d-hidalgo/azle-api-rest-ckbtc#1]
I am currently working on an Express.js application that integrates with Internet Computer Protocol (ICP) using the Azle framework. In the process of building my application, I've come across the need to generate new Principals for users.

But I still confuse and see your repository azle-api-rest-ckbtc noticed that the `generateId()` function in your codebase generates random bytes to create a new Principal. However, I am concerned that this method may not align with the best practices recommended by DFINITY, especially in terms of security and validity.

Could you please provide guidance or point me to the relevant documentation on the best practices for generating Principals within an Express.js application using Azle? I want to ensure that the Principals generated are both secure and compatible with the ICP network.

**Comment by adrian-d-hidalgo** [comment]
generateId that you mentioned is a function proposed by the official Azle examples, I haven't yet analyzed the security and validity of it, I used it only for demo purposes, if you want to improve that code you can use the caller() like this:

`const id = ic.caller();`

Then you aren't generating the principal, you are using the principal from a signed identity.

**Comment by wirapratamaz** [comment]
Thank you for addressing this concern and providing insight into the usage of generateId() within the Azle framework. I'll proceed with implementing `ic.caller()` in place of generateId() in my application to ensure standards.
